apiVersion: v1
kind: Service
metadata:
  name: csr-staging-app
spec:
  type: NodePort
  selector:
    app: csr-staging-app
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30081
