apiVersion: v1
kind: Service
metadata:
  name: docktools-portfolio
spec:
  type: NodePort
  selector:
    app: docktools-portfolio
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
